### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Kyjor** [YongHee-Kim/GameDataManager.jl#8]
Hello, I'm getting to the point where I would like to use this in the coming months. At the moment, I think the potential of using this for localization would be amazing for me. I would like to put in a feature request for this. Thanks!

**Comment by YongHee-Kim** [comment]
Hello, Yes that makes a lot of sense. The `GameDataManager.jl` actually have a localization support https://github.com/YongHee-Kim/GameDataManager.jl/blob/main/src/localizer.jl 
Which were built to extract localization data in a JSON format for https://lokalise.com/ 

I will test GameDataManager.jl on the Julia latest and add tutorial for localization setting

**Comment by Kyjor** [comment]
That would be great, thank you! I wasn't sure the state of it based on the readme. Having some instructions will be super helpful

**Comment by Kyjor** [comment]
Using this for a new project now and figured the localization out I think. Thanks for updating the readme! I'll make sure to send the project by when it's ready!
